<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>openqa.automation.framework</groupId>
    <artifactId>sloth-java</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>sloth-java</name>
    <description>Parent aggregator for sloth-java modules</description>

    <modules>
        <module>test-automation-framework</module>
        <module>spring-boot-demo</module>
    </modules>
</project>
