AMAZON_URL = https://www.amazon.com/
BARCODE_BASE_URL = https://cineplex-apis-nonprod.azure-api.net/
CONNECT_URL = https://apis.cineplex.com/uat/connect/v1
BROWSER = chrome
GLOBAL_TIMEOUT = 10
MAX_RETRY_COUNT = 3
EXPLICIT_WAIT_TIME = 10
IMPLICIT_WAIT_TIME = 5
PAGE_LOAD_TIMEOUT = 3
PAGE_RENDER_TIMEOUT = 3