package Scenarios.UI;// Generated by Selenium IDE

import com.utilities.SeleniumWrapper;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;

public class GoogleHomepageTest {
    private static WebDriver driver;

    @Before
    public void setUp() {
        driver = SeleniumWrapper.createDriver("chrome");
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void googleHomepage() {
        driver.get("https://www.google.com/");
        driver.findElement(By.name("q")).sendKeys("automation");
        SeleniumWrapper.waitForPageLoadCompletion(driver);
        driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
        SeleniumWrapper.waitForPageLoadCompletion(driver);
    }
}
