
// Generated by Selenium IDE
import config.Constants;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.io.File;
import java.net.MalformedURLException;

public class GoogleAutomationHomepageTest {
	private static WebDriver driver;
	JavascriptExecutor js;

	@Before
	public void setUp() throws MalformedURLException {
		File file = new File(Constants.WIN64_DRIVER_FIREFOX);
		System.setProperty("webdriver.gecko.driver", file.getAbsolutePath());
		System.out.println(file.getAbsolutePath());
		driver = new FirefoxDriver();
		driver.manage().window().maximize();
		((JavascriptExecutor) driver).executeScript("window.focus();");
	}

	@After
	public void tearDown() {
		// driver.quit();
	}

	@Test
	public void googleautomationhomepage() {
		driver.get("https://www.google.ca/");
		driver.manage().window().setSize(new Dimension(866, 466));
		driver.findElement(By.name("q")).click();
		driver.findElement(By.name("q")).sendKeys("automation");
		driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
	}
}
