package scenarios.UI.google;// Generated by Selenium IDE

import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.testng.annotations.Test;
import testcases.GuiTestCase;
import testcases.TestGroups;
import utilities.SeleniumWrapper;
import webpages.BaseWebPage;

public class TestGoogleHomepage extends GuiTestCase {
    @Test(groups = {TestGroups.REGRESSION, TestGroups.SMOKE, TestGroups.UI_WEB})
    public void googleHomepage() {
        driver = BaseWebPage.getDriver("chrome");
        driver.get("https://www.google.com/");
        driver.findElement(By.name("q")).sendKeys("automation");
        SeleniumWrapper.waitForPageLoadCompletion(driver);
        driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
        SeleniumWrapper.waitForPageLoadCompletion(driver);
    }
}
